### ISSUE TITLE
Please remove social media tracking

### ISSUE THREAD

**Issue by onedrawingperday** [marcanuy/simpleit-hugo-theme#24]
Hello I am one of the maintainers of [Hugo Themes](https://themes.gohugo.io/).

As described in https://github.com/gohugoio/hugoThemes/issues/564 your theme features share buttons from social media networks that track users in `\simpleit-hugo-theme\layouts\partials\share_buttons.html:`

I kindly request that you remove the tracking code. 

I understand that your theme has been approved with the tracking code but currently the guidelines for maintaining a theme on the Hugo Themes list are about to change and the requirement to not include tracking in Hugo Themes will be included in the new guidelines.

I suggest that you re-write to the above partial as described in this resource: https://sharingbuttons.io

If you have any questions then please do not hesitate to ask.

Looking forward to your reply.

cc: @digitalcraftsman

**Comment by marcanuy** [comment]
Hello @onedrawingperday , I am already using a static version for share buttons by default.

After reading https://github.com/gohugoio/hugoThemes/issues/535 and 
https://github.com/gohugoio/hugoThemes/issues/564 I understand that the requirement is to not have them enabled in the Hugo Themes site.

By default this theme demo uses a static set of buttons [partial](https://github.com/marcanuy/simpleit-hugo-theme/blob/master/layouts/partials/share_static.html) based in https://sharingbuttons.io which is the one published in Hugo Themes site.

The partial you referenced uses a configuration parameter that let the user decide the static or dynamic version:

~~~
  # Render Share buttons static or with javascript
  shareButtonsType = "static" #<static|javascript>
~~~

which is being used at [share_buttons.html](https://github.com/marcanuy/simpleit-hugo-theme/blob/master/layouts/partials/share_buttons.html)

~~~
    {{ if (eq .Site.Params.shareButtonsType "static")}}
    {{ partial "share_static.html" . }}
    {{else}}
    //  load dynamic ones
    {{end}}
~~~

Please let me know if you have any questions about it.

cc @digitalcraftsman

**Comment by onedrawingperday** [comment]
@marcanuy 

Thank you for clarifying.
