### ISSUE TITLE
Theme demo broken on the Hugo Themes website

### ISSUE THREAD

**Issue by onedrawingperday** [marcanuy/simpleit-hugo-theme#25]
Hello @marcanuy 

Currently the theme demo on the Hugo Themes website is broken due to gohugoio/hugo#7036

To fix the theme demo please regenerate and commit the theme's resources.

Once you do this feel free to close this issue and then I will update the theme on the Hugo Themes repo.

Thanks.

**Comment by marcanuy** [comment]
@onedrawingperday Thanks, please let me know If it requires any further changes.
